name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kage-lite-development/kage-lite

  checkoutLFS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Check out LFS objects
        run: git lfs pull

  showCondaEnvironment:
    needs: [buildDocker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show Conda environment
        run: docker run -t kage-lite-development/kage-lite conda list

  runTests:
    needs: [buildDocker, checkoutLFS]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration pytests
        run: docker run --shm-size 4G -v ${{ github.workspace }}/kage/tests/resources:/kage-lite/kage/tests/resources -t kage-lite-development/kage-lite pytest /kage-lite/kage/tests/test_pipeline.py
