name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildDockerAndRunPytests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Check out LFS objects
      run: git lfs pull
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kage-lite-development/kage-lite
    - name: Run integration pytests
      run: docker run -t kage-lite-development/kage-lite pytest kage/tests/test_pipeline.py
